### ISSUE TITLE
Clearer error reporting when running a cell with expired auth connection

### ISSUE THREAD

**Issue by joyceerhl** [DonJayamanne/vscode-kusto#24]
1. Let kusto cluster auth expire
2. Run a *.knb cell. It fails with no error message
3. Run Notebook: Configure Kusto Cluster command to reconfigure auth
4. Run the same *.knb cell. It continues to fail with no error message
5. Reload VS Code and everything starts working again

For 2), would be nice to add error messages in cell outputs. For 4), seemed like errors were getting cached somehow? Would be nice to avoid that or make it clearer to the user that that's what's happening.

**Comment by DonJayamanne** [comment]
I've run into this at least 10-15 times today.

**Comment by joyceerhl** [comment]
![image](https://user-images.githubusercontent.com/30305945/113818196-4ceeb680-972c-11eb-9abd-1fd6bc6905a6.png)

This is all I get in the auth token timeout scenario, BTW, and I can reliably reproduce it. I know why this is happening, will submit a PR
